language: objective-c
before_install:
- "./scripts/before_install.sh"
install: echo "install"
before_script: echo "before_script"
script: echo "script"
after_success: echo "after_success"
after_failure: echo "after_failure"
after_script:
- "./scripts/after_script.sh"
