language: objective-c
before_install:
- openssl aes-256-cbc -K $encrypted_ca46b9fbacb2_key -iv $encrypted_ca46b9fbacb2_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- "./scripts/before_install.sh"
install: echo "install"
before_script: echo "before_script"
script: echo "script"
after_success: echo "after_success"
after_failure: echo "after_failure"
after_script: 
  - "./scripts/after_script.sh"
